# Generated by Django 3.0.4 on 2020-08-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mekan', '0002_remove_mekan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mekan',
            name='sehir',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mekan',
            name='ulke',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
