# Generated by Django 3.0.4 on 2020-08-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mekan', '0003_auto_20200807_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('mekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mekan.Mekan')),
            ],
        ),
    ]
